import java.util.Random;

public class Prompts {
    Random random = new Random();
    String newPrompt;
    public String Prompts(){
        int n = random.nextInt(301) + 1;
        switch (n){
            case 1: newPrompt = "Ice cream flavors";
                break;
            case 2: newPrompt = "Pets";
                break;
            case 3: newPrompt = "Things with tires";
                break;
            case 4: newPrompt = "Toys";
                break;
            case 5: newPrompt = "Streaming devices";
                break;
            case 6: newPrompt = "Wars";
                break;
            case 7: newPrompt = "Capitals east of the Mississippi";
                break;
            case 8: newPrompt = "Pies";
                break;
            case 9: newPrompt = "California cities";
                break;
            case 10: newPrompt = "Camping equipment";
                break;
            case 11: newPrompt = "Tools";
                break;
            case 12: newPrompt = "East coast states";
                break;
            case 13: newPrompt = "Rivers";
                break;
            case 14: newPrompt = "Things in the sky";
                break;
            case 15: newPrompt = "Colors";
                break;
            case 16: newPrompt = "Airline companies";
                break;
            case 17: newPrompt = "Spices";
                break;
            case 18: newPrompt = "Items in a wallet";
                break;
            case 19: newPrompt = "Fruits";
                break;
            case 20: newPrompt = "Sports with balls";
                break;
            case 21: newPrompt = "TV kids";
                break;
            case 22: newPrompt = "Countries in Africa";
                break;
            case 23: newPrompt = "Islands";
                break;
            case 24: newPrompt = "Car manufacturers";
                break;
            case 25: newPrompt = "Cheeses";
                break;
            case 26: newPrompt = "Muppets";
                break;
            case 27: newPrompt = "Hobbies";
                break;
            case 28: newPrompt = "Broadway musicals";
                break;
            case 29: newPrompt = "Animals/insects people are afraid of";
                break;
            case 30: newPrompt = "Holidays";
                break;
            case 31: newPrompt = "Awards ceremonies";
                break;
            case 32: newPrompt = "Emotions";
                break;
            case 33: newPrompt = "Breakfast cereals";
                break;
            case 34: newPrompt = "Car parts";
                break;
            case 35: newPrompt = "Types of furniture";
                break;
            case 36: newPrompt = "Languages";
                break;
            case 37: newPrompt = "Things you inflate";
                break;
            case 38: newPrompt = "Dog breeds";
                break;
            case 39: newPrompt = "European countries";
                break;
            case 40: newPrompt = "vegetables";
                break;
            case 41: newPrompt = "Foods at a barbecue";
                break;
            case 42: newPrompt = "TV sitcoms";
                break;
            case 43: newPrompt = "Things a baby does";
                break;
            case 44: newPrompt = "Card games";
                break;
            case 45: newPrompt = "Things in an attic";
                break;
            case 46: newPrompt = "Snack foods";
                break;
            case 47: newPrompt = "Hotel/Motel chains";
                break;
            case 48: newPrompt = "Soft drinks";
                break;
            case 49: newPrompt = "Things at a circus";
                break;
            case 50: newPrompt = "Sun ________";
                break;
            case 51: newPrompt = "Famous Superheroes";
                break;
            case 52: newPrompt = "Summer wear";
                break;
            case 53: newPrompt = "Ancient Greek gods";
                break;
            case 54: newPrompt = "Zoo animals";
                break;
            case 55: newPrompt = "Foreign currencies";
                break;
            case 56: newPrompt = "Famous Toms";
                break;
            case 57: newPrompt = "Animals with horns";
                break;
            case 58: newPrompt = "Mythical creatures";
                break;
            case 59: newPrompt = "Lady ______";
                break;
            case 60: newPrompt = "Things in a bakery";
                break;
            case 61: newPrompt = "Cold places";
                break;
            case 62: newPrompt = "People at a wedding";
                break;
            case 63: newPrompt = "Mobile apps";
                break;
            case 64: newPrompt = "Items that are plugged into a computer";
                break;
            case 65: newPrompt = "Sharp things";
                break;
            case 66: newPrompt = "Things in a bedroom";
                break;
            case 67: newPrompt = "Candy brands";
                break;
            case 68: newPrompt = "Medical specialties";
                break;
            case 69: newPrompt = "Blue _______";
                break;
            case 70: newPrompt = "Types of cookies (no brands)";
                break;
            case 71: newPrompt = "Half _______";
                break;
            case 72: newPrompt = "Things in Australia";
                break;
            case 73: newPrompt = "Common fears";
                break;
            case 74: newPrompt = "Musical instruments";
                break;
            case 75: newPrompt = "Comic strips";
                break;
            case 76: newPrompt = "Things people shout";
                break;
            case 77: newPrompt = "Traffic signs";
                break;
            case 78: newPrompt = "Meryl streep movies";
                break;
            case 79: newPrompt = "Fried _______";
                break;
            case 80: newPrompt = "Classic board games";
                break;
            case 81: newPrompt = "TV game shows";
                break;
            case 82: newPrompt = "Tourist attractions";
                break;
            case 83: newPrompt = "Sea creatures";
                break;
            case 84: newPrompt = "Things you microwave";
                break;
            case 85: newPrompt = "Apple ______";
                break;
            case 86: newPrompt = "Problems associated with getting old";
                break;
            case 87: newPrompt = "Mr. _______";
                break;
            case 88: newPrompt = "Things with a handle";
                break;
            case 89: newPrompt = "Types of fish";
                break;
            case 90: newPrompt = "Famous horror movies";
                break;
            case 91: newPrompt = "Sweet _______";
                break;
            case 92: newPrompt = "Amusement park rides";
                break;
            case 93: newPrompt = "Hot beverages";
                break;
            case 94: newPrompt = "Grocery store aisles";
                break;
            case 95: newPrompt = "Winter sports";
                break;
            case 96: newPrompt = "Famous action movies";
                break;
            case 97: newPrompt = "Hotel/Motel chains";
                break;
            case 98: newPrompt = "Soft drinks";
                break;
            case 99: newPrompt = "Things at a circus";
                break;
            case 100: newPrompt = "Sun ________";
                break;
            case 101: newPrompt = "Gym equipment";
                break;
            case 102: newPrompt = "High school subjects";
                break;
            case 103: newPrompt = "Beatles songs";
                break;
            case 104: newPrompt = "Household appliances";
                break;
            case 105: newPrompt = "Types of nuts";
                break;
            case 106: newPrompt = "Things in a courtroom";
                break;
            case 107: newPrompt = "Superstitions";
                break;
            case 108: newPrompt = "Radio station formats";
                break;
            case 109: newPrompt = "Nursery rhymes";
                break;
            case 110: newPrompt = "Things that are raced";
                break;
            case 111: newPrompt = "Doctor _______";
                break;
            case 112: newPrompt = "Things found on a map";
                break;
            case 113: newPrompt = "Kinds of trees";
                break;
            case 114: newPrompt = "Summer olympic events";
                break;
            case 115: newPrompt = "US landmarks";
                break;
            case 116: newPrompt = "Things in outer space";
                break;
            case 117: newPrompt = "Backyard items";
                break;
            case 118: newPrompt = "Items in a student backpack";
                break;
            case 119: newPrompt = "Mexican dishes";
                break;
            case 120: newPrompt = "Construction vehicles";
                break;
            case 121: newPrompt = "Types of birds";
                break;
            case 122: newPrompt = "Items used by a doctor";
                break;
            case 123: newPrompt = "Winter clothes";
                break;
            case 124: newPrompt = "Things that have doors";
                break;
            case 125: newPrompt = "Famous couples";
                break;
            case 126: newPrompt = "Book categories at a bookstore";
                break;
            case 127: newPrompt = "Football teams";
                break;
            case 128: newPrompt = "Clothing manufacturers";
                break;
            case 129: newPrompt = "Pizza toppings";
                break;
            case 130: newPrompt = "Things that have wings";
                break;
            case 131: newPrompt = "Sneaker brands";
                break;
            case 132: newPrompt = "Business trip expenses";
                break;
            case 133: newPrompt = "Mother ________";
                break;
            case 134: newPrompt = "Things that are folded";
                break;
            case 135: newPrompt = "Types of pasta";
                break;
            case 136: newPrompt = "Items in a science lab";
                break;
            case 137: newPrompt = "Constellations";
                break;
            case 138: newPrompt = "Places kids go for fun";
                break;
            case 139: newPrompt = "Things seen on a farm";
                break;
            case 140: newPrompt = "Summer camp activities";
                break;
            case 141: newPrompt = "Extreme sports";
                break;
            case 142: newPrompt = "Things on a playground";
                break;
            case 143: newPrompt = "Cable channels";
                break;
            case 144: newPrompt = "Things that are sticky";
                break;
            case 145: newPrompt = "Famous painters";
                break;
            case 146: newPrompt = "Countries of the world";
                break;
            case 147: newPrompt = "Things you bake";
                break;
            case 148: newPrompt = "Things made of leather";
                break;
            case 149: newPrompt = "US presidents";
                break;
            case 150: newPrompt = "Things that are thrown";
                break;
            case 151: newPrompt = "Types of dances";
                break;
            case 152: newPrompt = "Old school video games";
                break;
            case 153: newPrompt = "Create your own";
                break;
            case 154: newPrompt = "Things seen at a parade";
                break;
            case 155: newPrompt = "Cosmetic brands";
                break;
            case 156: newPrompt = "Things in a post office";
                break;
            case 157: newPrompt = "Countries in Asia";
                break;
            case 158: newPrompt = "Things seen at a picnic";
                break;
            case 159: newPrompt = "Breakfast foods";
                break;
            case 160: newPrompt = "High paying professions";
                break;
            case 161: newPrompt = "Create your own";
                break;
            case 162: newPrompt = "Modes of transportation";
                break;
            case 163: newPrompt = "Office supplies";
                break;
            case 164: newPrompt = "Things you celebrate";
                break;
            case 165: newPrompt = "Create your own";
                break;
            case 166: newPrompt = "Sections of a newspaper";
                break;
            case 167: newPrompt = "Tropical places";
                break;
            case 168: newPrompt = "Famous cats (no breeds)";
                break;
            case 169: newPrompt = "Famous athletes";
                break;
            case 170: newPrompt = "Famous dogs (no breeds)";
                break;
            case 171: newPrompt = "Valentine’s day gifts";
                break;
            case 172: newPrompt = "Items used when cleaning";
                break;
            case 173: newPrompt = "Signs of spring";
                break;
            case 174: newPrompt = "Items used by a magician";
                break;
            case 175: newPrompt = "Bagel varieties";
                break;
            case 176: newPrompt = "Things in a refrigerator";
                break;
            case 177: newPrompt = "Famous brothers";
                break;
            case 178: newPrompt = "Things made out of glass";
                break;
            case 179: newPrompt = "Disney villains";
                break;
            case 180: newPrompt = "Things the military uses";
                break;
            case 181: newPrompt = "Apple varieties";
                break;
            case 182: newPrompt = "Things people often lose";
                break;
            case 183: newPrompt = "Items in a purse";
                break;
            case 184: newPrompt = "Things that are colorful";
                break;
            case 185: newPrompt = "Famous comedians";
                break;
            case 186: newPrompt = "Things that have a shell";
                break;
            case 187: newPrompt = "Kinds of flowers";
                break;
            case 188: newPrompt = "Countries in South America";
                break;
            case 189: newPrompt = "Types of jewelry";
                break;
            case 190: newPrompt = "Things that come in jars";
                break;
            case 191: newPrompt = "______ sandwich";
                break;
            case 192: newPrompt = "Chinese dishes";
                break;
            case 193: newPrompt = "Types of weather";
                break;
            case 194: newPrompt = "Popular websites";
                break;
            case 195: newPrompt = "Things on a desk";
                break;
            case 196: newPrompt = "Tom hanks movies";
                break;
            case 197: newPrompt = "Kitchen utensils";
                break;
            case 198: newPrompt = "New York ________";
                break;
            case 199: newPrompt = "Types of insects";
                break;
            case 200: newPrompt = "Household chores";
                break;
            case 201: newPrompt = "Parts of a house";
                break;
            case 202: newPrompt = "Women in history";
                break;
            case 203: newPrompt = "Things at a bank";
                break;
            case 204: newPrompt = "Things that melt";
                break;
            case 205: newPrompt = "Things that come in pairs";
                break;
            case 206: newPrompt = "Workers who wear uniforms";
                break;
            case 207: newPrompt = "Police/detective TV shows";
                break;
            case 208: newPrompt = "Common halloween costumes";
                break;
            case 209: newPrompt = "Things in the garden";
                break;
            case 210: newPrompt = "Famous cartoon characters";
                break;
            case 211: newPrompt = "Items used by fishermen";
                break;
            case 212: newPrompt = "Things that have a remote";
                break;
            case 213: newPrompt = "Classical music composers";
                break;
            case 214: newPrompt = "Things people do to relax";
                break;
            case 215: newPrompt = "Places that are very dark";
                break;
            case 216: newPrompt = "Ice cream sundae toppings";
                break;
            case 217: newPrompt = "Colleges and universities";
                break;
            case 218: newPrompt = "Things people look through";
                break;
            case 219: newPrompt = "Things made with chocolate";
                break;
            case 220: newPrompt = "Switches/controls on a car";
                break;
            case 221: newPrompt = "Animals that live in trees";
                break;
            case 222: newPrompt = "Things Hawaii is known for";
                break;
            case 223: newPrompt = "Things used by a rock band";
                break;
            case 224: newPrompt = "Famous advertising slogans";
                break;
            case 225: newPrompt = "Things in The Wizard of Oz";
                break;
            case 226: newPrompt = "Jobs kids do to earn money";
                break;
            case 227: newPrompt = "Things found in the desert";
                break;
            case 228: newPrompt = "Things found in a basement";
                break;
            case 229: newPrompt = "Stores at the mall";
                break;
            case 230: newPrompt = "Things used in a bathroom";
                break;
            case 231: newPrompt = "Professional football teams";
                break;
            case 232: newPrompt = "Classic arcade games";
                break;
            case 233: newPrompt = "Washington DC attractions";
                break;
            case 234: newPrompt = "Professions that wear a hat";
                break;
            case 235: newPrompt = "Things found in an aquarium";
                break;
            case 236: newPrompt = "Fast food restaurant chains";
                break;
            case 237: newPrompt = "Things England is known for";
                break;
            case 238: newPrompt = "Items at a dentists office";
                break;
            case 239: newPrompt = "Types of juices (no brands)";
                break;
            case 240: newPrompt = "Vehicles with lights on top";
                break;
            case 241: newPrompt = "Things found in a freezer";
                break;
            case 242: newPrompt = "Things that live underground";
                break;
            case 243: newPrompt = "Things seen on a golf course";
                break;
            case 244: newPrompt = "Well-known statues/monuments";
                break;
            case 245: newPrompt = "Things people do on a cruise";
                break;
            case 246: newPrompt = "Bills people pay every month";
                break;
            case 247: newPrompt = "Things you find at a beach";
                break;
            case 248: newPrompt = "Male names beginning with J";
                break;
            case 249: newPrompt = "Popular vacation destinations";
                break;
            case 250: newPrompt = "Jobs that work mostly outside";
                break;
            case 251: newPrompt = "Things in a college dorm room";
                break;
            case 252: newPrompt = "Kinds of footwear (no brands)";
                break;
            case 253: newPrompt = "Male names beginning with S";
                break;
            case 254: newPrompt = "Things people use to stay warm";
                break;
            case 255: newPrompt = "Excuses for being late to work";
                break;
            case 256: newPrompt = "Popular children’s books";
                break;
            case 257: newPrompt = "Things associated with pirates";
                break;
            case 258: newPrompt = "Things that go round and round";
                break;
            case 259: newPrompt = "Things you do when sick";
                break;
            case 260: newPrompt = "Reasons people use the internet";
                break;
            case 261: newPrompt = "Equipment used when working out";
                break;
            case 262: newPrompt = "Things at a graduation ceremony";
                break;
            case 263: newPrompt = "Things people do in the morning ";
                break;
            case 264: newPrompt = "Female names beginning with S";
                break;
            case 265: newPrompt = "Things people do to look better";
                break;
            case 266: newPrompt = "Female names beginning with M";
                break;
            case 267: newPrompt = "Things people clean in the house";
                break;
            case 268: newPrompt = "Pixar movies";
                break;
            case 269: newPrompt = "Foods often eaten at thanksgiving";
                break;
            case 270: newPrompt = "Reasons for giving greeting cards";
                break;
            case 271: newPrompt = "Departments in a department store";
                break;
            case 272: newPrompt = "Things that are filled with water";
                break;
            case 273: newPrompt = "Professions that usually dress up";
                break;
            case 274: newPrompt = "Things that are often in a basket";
                break;
            case 275: newPrompt = "Things people do when sad";
                break;
            case 276: newPrompt = "Things at a child’s birthday party";
                break;
            case 277: newPrompt = "Things people do on new year’s eve";
                break;
            case 278: newPrompt = "Movie genres";
                break;
            case 279: newPrompt = "Foods that are sliced";
                break;
            case 280: newPrompt = "Home improvement store departments";
                break;
            case 281: newPrompt = "Items used with horses";
                break;
            case 282: newPrompt = "Things done at a wedding reception";
                break;
            case 283: newPrompt = "Things found in a medicine cabinet";
                break;
            case 284: newPrompt = "4-letter body parts";
                break;
            case 285: newPrompt = "MLB teams";
                break;
            case 286: newPrompt = "Household items that use batteries";
                break;
            case 287: newPrompt = "Things fans do at an athletic events";
                break;
            case 288: newPrompt = "Things a police officer does";
                break;
            case 289: newPrompt = "Things people store in their garage";
                break;
            case 290: newPrompt = "Things at an airport";
                break;
            case 291: newPrompt = "Books many people have in their homes";
                break;
            case 292: newPrompt = "Nicknames for money";
                break;
            case 293: newPrompt = "What kids want to be when they grow up";
                break;
            case 294: newPrompt = "Major annual televised events";
                break;
            case 295: newPrompt = "Things in an elementary school classroom";
                break;
            case 296: newPrompt = "Punctuation marks";
                break;
            case 297: newPrompt = "People who work in the middle of the night";
                break;
            case 298: newPrompt = "Popular magazines";
                break;
            case 299: newPrompt = "Things people do before falling asleep";
                break;
            case 300: newPrompt = "Things people sit on";
                break;
            case 301: newPrompt = "Things associated with France";
                break;
        }
        return newPrompt;
    }
}
